apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: red-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: red
  template: 
    metadata:
      labels:
        app: red
    spec:
      containers:
      - name: red
        image: codegazers/colors:1.12
        ports:
        - containerPort: 3000
        env:
        - name: COLOR
          value: "red"
        readinessProbe:
          httpGet:
            port: 3000
            path: /health
            httpHeaders:
            - name: AppStatus
              value: "UP"
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 4
          successThreshold: 2
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: red-svc
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: red
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blue-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue
  template: 
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: codegazers/colors:1.12
        ports:
        - containerPort: 3000
        env:
        - name: COLOR
          value: "blue"
        readinessProbe:
          httpGet:
            port: 3000
            path: /health
            httpHeaders:
            - name: AppStatus
              value: "UP"
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 4
          successThreshold: 2
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: blue-svc
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: blue
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: black-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: black
  template: 
    metadata:
      labels:
        app: black
    spec:
      containers:
      - name: black
        image: codegazers/colors:1.12
        ports:
        - containerPort: 3000
        env:
        - name: COLOR
          value: "black"
        readinessProbe:
          httpGet:
            port: 3000
            path: /health
            httpHeaders:
            - name: AppStatus
              value: "UP"
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 4
          successThreshold: 2
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: black-svc
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: black
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: white-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: white
  template: 
    metadata:
      labels:
        app: white
    spec:
      containers:
      - name: white
        image: codegazers/colors:1.12
        ports:
        - containerPort: 3000
        env:
        - name: COLOR
          value: "white"
        readinessProbe:
          httpGet:
            port: 3000
            path: /health
            httpHeaders:
            - name: AppStatus
              value: "UP"
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 4
          successThreshold: 2
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: white-svc
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: white
---